sonar.projectKey=GabrielUPTCHE_frontend-casualidad-app
sonar.organization=sonar-projects-sw
sonar.projectVersion=1.0

# Dónde está el código fuente (Angular usa src)
sonar.sources=src

# Qué archivos NO debe analizar buscando bugs (pruebas, configuraciones, etc.)
sonar.exclusions=src/**/*.spec.ts, src/**/*.d.ts, src/setup-jest.ts, src/environments/**, src/main.ts

# Dónde están los archivos de pruebas
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

# --- AQUÍ OCURRE LA MAGIA DEL ENLACE ---
# Le decimos a SonarQube dónde dejó Jest el reporte de cobertura
sonar.javascript.lcov.reportPaths=coverage/frontend-casualidad-app/lcov.info

sonar.token=ccad72e9c38ae4435a115cd54e86dd2c2610d9f4
