sonar.projectKey=GabrielUPTCHE_frontend-casualidad-app
sonar.organization=sonar-projects-sw
sonar.projectVersion=1.0

# Dónde está el código fuente (Angular usa src)
sonar.sources=src
sonar.tests=src

sonar.exclusions=src/**/*.spec.ts, src/**/*.d.ts, src/setup-jest.ts, src/environments/**, src/main.ts

sonar.test.inclusions=src/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/frontend-casualidad-app/lcov.info

